### ISSUE TITLE
can it be used on Windows?

### ISSUE THREAD

**Issue by Sandy4321** [momacs/pram#1]
can it be used on Windows?

**Comment by ubiq-x** [comment]
I don't see why not.  It currently depends on pretty stock-standard libraries (i.e., scipy, numpy, and attrs).

**Comment by Sandy4321** [comment]
great thanks
this is also new idea
https://github.com/Guillemdb/FractalAI
https://www.youtube.com/watch?v=rZpZU8LHPco
Guillem Duran - Hacking Reinforcement Learning
